[package]
name = "aoc-24"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "aoc-24"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
num-traits = "0.2.19"
regex = "1.11.1"
utils = { version = "0.1.0", path = "../utils" }
